### ISSUE TITLE
Unix domain socket support

### ISSUE THREAD

**Issue by danielsig727** [johnmanjiro13/tokio-fluent#46]
Hello, 
I have a fork of this repo to support sending logs to fluentd server using unix socket files instead of TCP. The change is simple  (commit: https://github.com/johnmanjiro13/tokio-fluent/compare/main...danielsig727:tokio-fluent:uds_support ), and it's tested on my own project.

I'd like to back-port to here. However, I need your opinion on the interface change.
In my fork, for simplicity, I changed `fn new(config: &Config)` to `new_tcp(addr: SocketAddr, config: &Config)` and `new_unix(path: &str, config: &Config)`, and removed `addr` from `Config`. Another way could be keeping `fn new(config: &Config)` and `Config.addr` for backward compatibility, and adding `new_unix(path: &str, config: &Config)` but it neglects the `addr`. What do you think? Thank you

**Comment by johnmanjiro13** [comment]
Hi, @danielsig727. Thank you for your proposal.

Let me get straight to the point, I'd like to adopt your interface change.
Backward compatibility is important, but I'd like to avoid to use `new` only for tcp.
Also, I thought about to add `network` option to `Config` like an [official fluent logger](https://github.com/fluent/fluent-logger-golang/blob/5538e904aeb515c10a624da620581bdf420d4b8a/fluent/fluent.go#L435-L463), but it will increase complexity about configuration.

Could you create a pull request for this change?

**Comment by danielsig727** [comment]
sure. it's here: https://github.com/johnmanjiro13/tokio-fluent/pull/47
thank you!
