### ISSUE TITLE
Restore a connection when it is lost

### ISSUE THREAD

**Issue by johnmanjiro13** [johnmanjiro13/tokio-fluent#52]
ref: #50

We should reconnect if fluentd connection is lost by itself.

official golang
https://github.com/fluent/fluent-logger-golang/blob/5538e904aeb515c10a624da620581bdf420d4b8a/fluent/fluent.go#L523-L535

**Comment by danielsig727** [comment]
I also encountered this recently. IMO, reconnection should happen when 1) the pre-defined max connection lifetime has been reached, or 2) the number of retries exceeds a pre-defined threshold.  

Currently I'm re-creating a client from outside every X seconds as a workaround. But I think it's better handled inside the worker threads (or a new background thread maintaining the connection).  I might try it when I have time.

**Comment by johnmanjiro13** [comment]
Thank you @danielsig727 
I'm very busy and haven't been able to find the time to fix this issue.
If you can try it, I'm so glad.

> I think it's better handled inside the worker threads (or a new background thread maintaining the connection)

I agree with this opinion.

**Comment by danielsig727** [comment]
created an PR https://github.com/johnmanjiro13/tokio-fluent/issues/52 for this :D 
I've tested locally

**Comment by johnmanjiro13** [comment]
@danielsig727 I'm sorry for late review.
Thank you!

**Comment by johnmanjiro13** [comment]
v0.5.1 released.
https://github.com/johnmanjiro13/tokio-fluent/releases/tag/v0.5.1
